"""
PrimeForm Lab: a concept-first Blender add-on delivering generative blockouts,
silhouette-safe mesh relaxation, and flow-aware UV alignment to accelerate
modeling and texturing.
"""
import importlib
import bpy

bl_info = {
    "name": "PrimeForm Lab",
    "author": "Autogenerated by GPT-5.1-Codex-Max",
    "version": (0, 1, 0),
    "blender": (3, 0, 0),
    "location": "View3D > Sidebar > PrimeForm Lab",
    "description": "Generative blockouts, silhouette-safe relax, flow-aware UVs.",
    "warning": "Experimental toolkit",
    "category": "3D View",
}

# Modules to reload during development
from . import operators, ui

modules = [operators, ui]


def reload_modules():
    for module in modules:
        importlib.reload(module)


# Registration helpers
classes = []


def register():
    for module in modules:
        if hasattr(module, "register"):
            module.register(classes)
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
    for module in modules:
        if hasattr(module, "unregister"):
            module.unregister(classes)


if __name__ == "__main__":
    register()
